### ISSUE TITLE
 This repository is over its data quota

### ISSUE THREAD

**Issue by ZhangShurong** [twelveand0/alphadiff-dataset#1]
This repository is over its data quota

**Comment by twelveand0** [comment]
Yes. The default free space is 1Gb. I have paid for an extra LFS data pack (50Gb).

**Comment by twelveand0** [comment]
Hello, the repo can be cloned with **git-lfs** as the following:

1.  Install *git-lfs* as noted on [https://www.atlassian.com/git/tutorials/git-lfs#installing-git-lfs](https://www.atlassian.com/git/tutorials/git-lfs#installing-git-lfs)
2. git lfs clone https://github.com/twelveand0/alphadiff-dataset.git
